"""Add categories table

Revision ID: b999f3022f6f
Revises: 050d6ab72636
Create Date: 2026-01-18 15:05:07.871898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b999f3022f6f'
down_revision: Union[str, Sequence[str], None] = '050d6ab72636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('attempts', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('attempts', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quizzes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'time_limit')
    op.drop_column('quizzes', 'category_id')
    op.drop_column('attempts', 'completed_at')
    op.drop_column('attempts', 'started_at')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
